# Generated by Django 5.1.1 on 2024-11-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='country_name',
        ),
    ]
